###################################################
#
# Case of a subsonic inviscid NACA0012 profile
#
###################################################

# Inlet conditions
pressure = 1e5
mach = 0.2
temperature = 300.
nx = 1.
ny = 0.

# Outlet pressure
pout = 1e5

# Boundary atribuition (BC:boundary_name = boundary_type)
# Types of boundaries: wall, wallT, inlet, outlet, symmetry
BC:wall = wall
BC:wallFar = inlet
BC:inlet = inlet
BC:outlet = outlet

# Surface data extraction (insert the interest surface)
writeSurf = wall

# Max number of iterations
Nmax = 10000

# Order of the solver (1 or 2)
order = 2

# Number of threads (use the number of physical cores in the CPU)
threads = 4

# Type of convective flux scheme (ROE, AUSM, AUSMDV, AUSMpup, AUSMpup2)
flux = AUSMpup2

# Case is axisymmetric? (0 or 1)
axisymmetric = 0

# Time scheme (RK or LUSGS)
timeScheme = LUSGS

# Courant number (<= 1 for RK)
CFL = 1e3

# Start the case from a previous simulation? (0 or 1)
restart = 0

# w parameter in LUSGS (1 < wImp < 2)
wImp = 1.5

# K parameter in Venkatakrishnan limiter (limK < 5)
limK = 0.1
