###################################################
#
# Case of a shock tube with the Sod problem 
# configuration
#
###################################################

# First half initial conditions
pressure1 = 1e5
mach1 = 0.
temperature1 = 300.
nx1 = 1.
ny1 = 0.

# Second half initial conditions
pressure2 = 1e4
mach2 = 0.
temperature2 = 240.
nx2 = 1.
ny2 = 0.

# Boundary atribuition (BC:boundary_name = boundary_type)
# Types of boundaries: wall, wallT, inlet, outlet, symmetry
BC:wallUp = wall
BC:wallDown = wall
BC:wallRight = wall
BC:wallLeft = wall

# Surface data extraction (insert the interest surface)
writeSurf = wallUp

# Shock tube case flag (0 or 1)
tube = 1

# Separation x position
xm = 25.

# Final physical time
tmax = 0.02

# Order of the solver (1 or 2)
order = 2

# Number of threads (use the number of physical cores in the CPU)
threads = 4

# Type of convective flux scheme (ROE, AUSM, AUSMDV, AUSMpup, AUSMpup2)
flux = ROE

# Case is axisymmetric? (0 or 1)
axisymmetric = 0

# Time scheme (RK or LUSGS)
timeScheme = RK

# Courant number (<= 1 for RK)
CFL = 1.0

# Number of stages of Runge-Kutta (RK) scheme
stages = 5

# K parameter in Venkatakrishnan limiter (limK < 5)
limK = 0.01
